# Development exports
export TARGET=Packages
export PYRO_INCLUDE=/boot/Include
export PYRO_COMMON=$PYRO_INCLUDE/Common
export PYRO_BINARY_DESTINATION=$HOME/PyroBuild
export C_INCLUDE_PATH=$C_INCLUDE_PATH:$PYRO_INCLUDE
export CPLUS_INCLUDE_PATH=CPLUS_INCLUDE_PATH:$PYRO_INCLUDE
