#! /bin/sh

export BOOTTIME=`/boot/NIX/coreutils/bin/date --utc +%Y%m%d%H%M%S`

# This is the initialisation script for Pyro.
# 
# ************************************************************************** #
#                            DO NOT EDIT THIS FILE!                          #
# ************************************************************************** #
#
# init.sh is called directly by the init process; do not call this file
# yourself.
# This script in turn calls /etc/profile, user-early-init.sh, network-init.sh
# and user-init.sh  If you wish to modify your configuration or initialisation
# process you should edit these files instead.

# Log local kernel output into /boot/System/log/kernel
/boot/System/binary/dbterm 8 >> /boot/System/log/$BOOTTIME-kernel &
/boot/NIX/coreutils/bin/ln -sf /boot/System/log/$BOOTTIME-kernel /boot/System/log/kernel

# Configure basic environment.
# BASh runs this, too, but do it earlier for the benefit of processes started
# here.
source /boot/System/config/etc/profile

# Silently empty the temporary directory
if [ "$TEMP" != '' ]
then
	rm -rf $TEMP/* > /dev/null 2>&1
fi

# If the graphical login isn't available, failsafe to a standalone server and
# abort further initialisation
if [ ! -e /boot/System/binary/dlogin ]
then
	/boot/System/binary/Terminal &
	exit 1
fi

# Start the graphical login and servers
/boot/System/binary/dlogin < /dev/null >> /boot/System/log/$BOOTTIME-desktop 2>&1 &

# No more environment variables can be defined for the user's environment
# after DLogin has started

for SERVER in `ls -1 /boot/System/servers/`; do
	if [ -f /boot/System/servers/$SERVER ] ; then
		/boot/System/servers/$SERVER < /dev/null >> /boot/System/log/$BOOTTIME-$SERVER 2>&1 &
	fi
done;

# Check for network changes & configure the network if required
/boot/Preferences/Network --detect

source /boot/System/scripts/network-init.sh

# inetd is a special case and is always started first if INetUtils is
# installed.

if [ -e /boot/System/NIX/inetutils/libexec/inetd ]
then
	/boot/System/NIX/inetutils/libexec/inetd &
fi

# Do user initialisation and exit
source /boot/System/scripts/user-init.sh

exit 0
